export const privileges = [
	{
		id: 'legend',
		name: 'LEGEND',
		image: 'legend.png',
		icon: 'Crown',
		prices: {
			'1m': 669,
			'3m': 950,
			forever: 1300,
		},
		color: 'privilege-legend',
		features: [
			'Легендарная сила',
			'Максимальные привилегии',
			'Эксклюзивные возможности',
		],
		commands: [
			'Получить уникальный набор - /kit legend',
			'Подарить игроку донат - /grant',
			'Сменить псевдоним в игре - /nick',
			'Узнать реальный ник игрока - /realname',
			'Телепортация к игрокам - /rtp player',
			'Заблокировать игроку чат - /mute',
			'Улучшить снаряжение - /swithingtable',
			'Ударить молнией - /lightning',
		],
		additionalFeatures: [
			'Точек дома: 8',
			'Количество приватов: 5',
			'Слотов на аукционе: 25',
			'Все возможности предыдущих привилегий',
		],
	},
	{
		id: 'imperator',
		name: 'IMPERATOR',
		image: 'IMPERATOR.png',
		icon: 'Shield',
		prices: {
			'1m': 469,
			'3m': 639,
			forever: 789,
		},
		color: 'privilege-imperator',
		features: [
			'Императорская власть',
			'Командование армией',
			'Безграничные ресурсы',
		],
		commands: [
			'Уникальный набор - /kit imperator',
			'Размутить игрока - /unmute',
			'Открыть эндер-сундук игрока - /ec (ник)',
			'Найти игрока - /near',
			'Починка и снятие чар - /grindstone',
			'Выдать временный бан игроку - /tempban',
			'Возможность писать - подчёркнутым',
			'Возможность писать - зачёркнутым',
			'Возможность писать - жирным',
		],
		additionalFeatures: [
			'Точек дома: 7',
			'Количество приватов: 4',
			'Слотов на аукционе: 18',
			'Все возможности предыдущих привилегий',
		],
	},
	{
		id: 'deadly',
		name: 'DEADLY',
		image: 'deadly.png',
		icon: 'Flame',
		prices: {
			'1m': 369,
			'3m': 489,
			forever: 539,
		},
		color: 'privilege-deadly',
		features: ['Смертельные атаки', 'Мгновенные убийства', 'Темная магия'],
		commands: [
			'Уникальный набор - /kit deadly',
			'Открыть чужой инвентарь - /invsee',
			'Телепортация к базам игроков - /rtp base',
			'Возможность писать объявление - /broadcast',
			'Возможность редактировать книги - /book',
			'Виртуальная мусорка - /trash',
			'Автопринятие запросов на телепорт - /tpauto',
		],
		additionalFeatures: [
			'Точек дома: 7',
			'Количество приватов: 4',
			'Слотов на аукционе: 15',
			'Все возможности предыдущих привилегий',
		],
	},
	{
		id: 'shade',
		name: 'SHADE',
		image: 'shade.png',
		icon: 'Ghost',
		prices: {
			'1m': 269,
			'3m': 299,
			forever: 389,
		},
		color: 'privilege-shade',
		features: ['Невидимость', 'Теневые способности', 'Скрытность'],
		commands: [
			'Уникальный набор - /kit shade',
			'Починить все предметы - /fix all',
			'Выдать мут игроку - /tempmute',
			'Узнать индефикатор предмета - /dura',
			'Переключение глобального чата - /chattoggle',
		],
		additionalFeatures: [
			'Точек дома: 6',
			'Количество приватов: 3',
			'Слотов на аукционе: 12',
			'Все возможности предыдущих привилегий',
		],
	},
	{
		id: 'leader',
		name: 'LEADER',
		image: 'leader.png',
		icon: 'Star',
		prices: {
			'1m': 119,
			'3m': 189,
			forever: 249,
		},
		color: 'privilege-leader',
		features: [
			'Лидерские качества',
			'Управление командой',
			'Стратегические преимущества',
		],
		commands: [
			'Уникальный набор - /kit leader',
			'Пополнить здоровье - /heal',
			'Открыть виртуальный эндер-сундук - /ec',
			'Установить личное время суток - /ptime',
			'Починить один предмет - /fix',
			'Узнать высоту над уровнем моря - /depth',
		],
		additionalFeatures: [
			'Точек дома: 6',
			'Количество приватов: 3',
			'Слотов на аукционе: 10',
			'Все возможности предыдущих привилегий',
		],
	},
	{
		id: 'ambush',
		name: 'AMBUSH',
		image: 'ambush.png',
		icon: 'Eye',
		prices: {
			'1m': 49,
			'3m': 89,
			forever: 199,
		},
		color: 'privilege-ambush',
		features: ['Засадные атаки', 'Скрытное передвижение', 'Внезапные удары'],
		commands: [
			'Уникальный набор - /kit ambush',
			'Далёкая телепортация - /rtp long',
			'Потушить себя - /exp',
			'Игнорировать игрока - /ignore (ник)',
			'Очистить свой инвентарь - /clear',
		],
		additionalFeatures: [
			'Точек дома: 5',
			'Количество приватов: 3',
			'Слотов на аукционе: 8',
			'Все возможности предыдущих привилегий',
		],
	},
	{
		id: 'survivor',
		name: 'SURVIVOR',
		image: 'survivor.png',
		icon: 'Pickaxe',
		prices: {
			'1m': 29,
			'3m': 69,
			forever: 149,
		},
		color: 'privilege-survivor',
		features: [
			'Выживание в экстремальных условиях',
			'Быстрая регенерация',
			'Устойчивость к урону',
		],
		commands: [
			'Уникальный кит - /kit survivor',
			'Покормить себя - /feed',
			'Надеть блок на голову - /hat',
			'Узнать идентификатор предмета - /itemdb',
		],
		additionalFeatures: [
			'Точек дома: 5',
			'Количество приватов: 2',
			'Слотов на аукционе: 7',
		],
	},
]

export const cases = [
	{
		id: 'donation-case',
		name: 'КЕЙС С ДОНАТОМ',
		image: 'case donat.png',
		features: [
			'Содержит случайную привилегию',
			'Шанс на выпадение редких донатов',
		],
		additionalFeatures: [
			'Может выпасть: LEGEND, IMPERATOR, DEADLY, SHADE, LEADER, AMBUSH, SURVIVOR',
			'Чем больше кейсов, тем выше шанс на редкий донат!',
		],
		quantities: [
			{ id: '1', label: '1 шт.', price: 99 },
			{ id: '3', label: '3 шт.', price: 250 },
			{ id: '5', label: '5 шт.', price: 400 },
			{ id: '10', label: '10 шт.', price: 750 },
		],
	},
	{
		id: 'plexiki-case',
		name: 'КЕЙС С ПЛЕКСИКИ',
		image: 'case plexiki.png',
		features: [
			'Содержит случайное количество плексиков',
			'Плексики - это игровая валюта для особых покупок',
		],
		additionalFeatures: [
			'Может выпасть: от 50 до 5000 плексиков',
			'Отличный способ пополнить баланс!',
		],
		quantities: [
			{ id: '1', label: '1 шт.', price: 50 },
			{ id: '3', label: '3 шт.', price: 120 },
			{ id: '5', label: '5 шт.', price: 180 },
			{ id: '10', label: '10 шт.', price: 300 },
		],
	},
	{
		id: 'coin-case',
		name: 'КЕЙС С МОНЕТАМИ',
		image: 'case Mone.png',
		features: [
			'Содержит случайное количество монет',
			'Используйте монеты для покупки предметов в игре',
		],
		additionalFeatures: [
			'Может выпасть: от 100 до 10000 монет',
			'Идеально для быстрого старта!',
		],
		quantities: [
			{ id: '1', label: '1 шт.', price: 15 },
			{ id: '3', label: '3 шт.', price: 40 },
			{ id: '5', label: '5 шт.', price: 60 },
			{ id: '10', label: '10 шт.', price: 100 },
		],
	},
	{
		id: 'title-case',
		name: 'КЕЙС С ТИТУЛАМИ',
		image: 'case titul.png',
		features: [
			'Содержит случайный уникальный титул',
			'Выделитесь среди других игроков',
		],
		additionalFeatures: [
			'Более 50 различных титулов',
			'Некоторые титулы дают бонусы!',
		],
		quantities: [
			{ id: '1', label: '1 шт.', price: 20 },
			{ id: '3', label: '3 шт.', price: 50 },
			{ id: '5', label: '5 шт.', price: 80 },
			{ id: '10', label: '10 шт.', price: 130 },
		],
	},
]

export const durations = [
	{
		id: '1m',
		label: '1 месяц',
		sapphires: '+760 сапфиров',
	},
	{
		id: '3m',
		label: '3 месяца',
		sapphires: '+1200 сапфиров',
	},
	{
		id: 'forever',
		label: 'Навсегда',
		sapphires: '+1920 сапфиров',
	},
]