export const serverOnline = 150;

export const players = [
  {
    "id": 1,
    "ip": "192.168.1.1",
    "nickname": "Admin",
    "privilege": "LEGEND",
    "privilegeDuration": "forever",
    "title": "Серверный владыка",
    "coins": 100000,
    "plexiki": 5000,
    "donationCases": 10,
    "plexikiCases": 10,
    "coinCases": 10,
    "titleCases": 10,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T12:30:00Z"
  },
  {
    "id": 2,
    "ip": "192.168.1.2",
    "nickname": "Player1",
    "privilege": "SHADE",
    "privilegeDuration": "forever",
    "title": "Новичок",
    "coins": 500,
    "plexiki": 10,
    "donationCases": 1,
    "plexikiCases": 2,
    "coinCases": 5,
    "titleCases": 0,
    "isBanned": false,
    "isMuted": true,
    "lastActivity": "2025-08-05T11:00:00Z"
  },
  {
    "id": 3,
    "ip": "192.168.1.3",
    "nickname": "Player2",
    "privilege": "LEADER",
    "privilegeDuration": "1m",
    "title": "Ветеран",
    "coins": 15000,
    "plexiki": 100,
    "donationCases": 3,
    "plexikiCases": 5,
    "coinCases": 10,
    "titleCases": 2,
    "isBanned": true,
    "isMuted": false,
    "lastActivity": "2025-08-04T23:10:00Z"
  },
  {
    "id": 4,
    "ip": "192.168.1.4",
    "nickname": "Player3",
    "privilege": "SURVIVOR",
    "privilegeDuration": "forever",
    "title": "Император битв",
    "coins": 131200,
    "plexiki": 160,
    "donationCases": 10,
    "plexikiCases": 10,
    "coinCases": 0,
    "titleCases": 0,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T12:35:00Z"
  },
  {
    "id": 5,
    "ip": "192.168.1.5",
    "nickname": "SWA4_G",
    "privilege": "IMPERATOR",
    "privilegeDuration": "forever",
    "title": "Император битв",
    "coins": 75010,
    "plexiki": 0,
    "donationCases": 10,
    "plexikiCases": 5,
    "coinCases": 10,
    "titleCases": 10,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T12:35:00Z",
    "cases": {
      "donationCases": 5
    }
  },
  {
    "id": 6,
    "ip": "192.168.1.6",
    "nickname": "Shadow",
    "privilege": "SHADE",
    "privilegeDuration": "1m",
    "title": "Темный странник",
    "coins": 25000,
    "plexiki": 300,
    "donationCases": 2,
    "plexikiCases": 3,
    "coinCases": 7,
    "titleCases": 1,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T10:00:00Z"
  },
  {
    "id": 7,
    "ip": "192.168.1.7",
    "nickname": "Ambusher",
    "privilege": "AMBUSH",
    "privilegeDuration": "3m",
    "title": "Охотник",
    "coins": 10000,
    "plexiki": 50,
    "donationCases": 11,
    "plexikiCases": 1,
    "coinCases": 2,
    "titleCases": 0,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T09:45:00Z"
  },
  {
    "id": 8,
    "ip": "192.168.1.8",
    "nickname": "Survivor",
    "privilege": "LEGEND",
    "privilegeDuration": "1m",
    "title": "Выживший",
    "coins": 1000000,
    "plexiki": 300,
    "donationCases": 10,
    "plexikiCases": 0,
    "coinCases": 10,
    "titleCases": 0,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T08:20:00Z"
  },
  {
    "id": 9,
    "ip": "192.168.1.9",
    "nickname": "ImperatorFan",
    "privilege": "IMPERATOR",
    "privilegeDuration": "3m",
    "title": "Поклонник Императора",
    "coins": 50000,
    "plexiki": 1000,
    "donationCases": 5,
    "plexikiCases": 6,
    "coinCases": 8,
    "titleCases": 4,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T11:50:00Z"
  },
  {
    "id": 10,
    "ip": "192.168.1.10",
    "nickname": "Newbie",
    "privilege": "LEADER",
    "privilegeDuration": "forever",
    "title": "Новичок",
    "coins": 100,
    "plexiki": 5,
    "donationCases": 0,
    "plexikiCases": 1,
    "coinCases": 2,
    "titleCases": 0,
    "isBanned": false,
    "isMuted": false,
    "lastActivity": "2025-08-05T13:00:00Z"
  }
];
